### ISSUE TITLE
Note to initial commit

### ISSUE THREAD

**Issue by qqtop** [Skrylar/firebird#1]
Great effort to wrap the fbclient 

Tried to compile with     nim c ex01.nim   on linux.
ibase.h was not picked up initially but was ok when I gave it the full path
#{.passl: "-lfbembed".}  failed , after commenting out  I get this:

```
/data5/NimTests/firebird/examples/nimcache/ex01.o: In function `NimMainModule':
ex01.c:(.text+0x168): undefined reference to `isc_dsql_execute_immediate'
ex01.c:(.text+0x18e): undefined reference to `isc_commit_transaction'
ex01.c:(.text+0x19d): undefined reference to `isc_detach_database'
collect2: error: ld returned 1 exit status

```
In firebird3 there is no libfbembed.so , I think embedded connections are via libEngine12.so
which is set in the configuration files.

In case you continue this effort it might be best to connect with the firebird developers
at  [https://www.firebirdsql.org](https://www.firebirdsql.org) via their developers mailing-list.

I am sure they are able and happy  to answer any current and upcoming questions.

Maybe some of these manuals will help too:  [https://www.firebirdsql.org/en/reference-manuals/](https://www.firebirdsql.org/en/reference-manuals/) 

My current solution  [https://github.com/qqtop/NimFirebird](https://github.com/qqtop/NimFirebird)  is via the python driver , but in the long run a "pure" nim driver is the way to go. 

The firebird community is actually quite large and  active in Brasil,Russia,Germany and Czech.

**Comment by Skrylar** [comment]
Arch does not have Firebird 3.0, so I have to test the code against 2.5 (for now) which appears to be highly compatible. Except of course, `fbembed` is exclusive to 2.5. The Super Server, Classic Server and Embedded were consolidated in 3.0 and I believe all exist in the client package now. This testing problem ought to be fixed when I finish moving over to Debian Sid.
