### ISSUE TITLE
Embedded mode under 3.0?

### ISSUE THREAD

**Issue by Skrylar** [Skrylar/firebird#10]
Under 2.5, there is fbembed. Under 3.0, that doesn't exist. Installing the dev, common and client packages under Deb/Sid results in non-working examples (they "cannot connect to localhost.")

Trying to find docs to force embedded mode (if possible,) although its proving difficult.

**Comment by Skrylar** [comment]
https://stackoverflow.com/questions/26179554/unable-to-access-embedded-firebird-database-server-with-net-client
Says that the ODBC driver allows specifying embedded mode explicitly.  Firebird's own docs say that the embedded engine is now known as "Engine12" and is a plugin through a configuration setting. So far it appears you have to either 1) rely on the OS install of Firebird, and hope the user doesn't disable Engine12 or 2) vendor your own install, which might work for an AppImage but certainly is not allowed by distro maintainers.

**Comment by qqtop** [comment]
check your firebird.conf 
the section in question  reads (and it works for a superserver setup)
Note  some of the firebird2.5 configurations are not applicable to firebird3

```
# This parameter determines what providers will be used by firebird.
# Format is the same as for the list of plugins (see a few lines before).
# This is not strange because internally provider is just a kind of plugin.
#
# Type: string
#
# Per-database & per-connection configurable.
#
#Providers = Remote,Engine12,Loopback

```

**Comment by Skrylar** [comment]
That is the valid default, but still runs in to a (probably unfixable) problem:
- Users could screw up that conf and there's nothing we can do about it (despite being "embedded", configs outside our purview are being relied upon.) Can be solved by vendoring Firebird (ex. for wrapping up in an AppImage) but distro maintainers won't accept apps with vendored dependencies.
- Use the global install and pray users don't screw it up.
Neither of those situations are particularly peachy, esp. compared to Sqlite3 which users _can't_ screw up.

**Comment by Skrylar** [comment]
Some FreePascal wiki stuff (http://wiki.lazarus.freepascal.org/Firebird_embedded#Linux) talks about having issues with the lock directory. It seems that for some reason, none of the temporary directory commands are obeyed when it comes to lock files. This thread (This thread: http://firebird.1100200.n4.nabble.com/Linux-compilation-tmp-firebird-td2708805.html) names `FIREBIRD_LOCK` as the correct environment variable to set (I have yet to grep through and see if firebird.config supports this.) There is a temporary solution by setting this to a directory that is writable (ex. an app's own temp folder) but now has the hairy aspect of making us set envars in boot scripts.

~~Additionally when I test this on a second computer (using the lock envar, instead of adding myself to the `firebird` group) some weird invalid memory starts happening in fetches. Hmm. Having `firebird.conf` files in interesting places seems to cause some really messed up results to occur. Although removing the conf resulted in things working again.~~
